E_pump_uJ: 0.001
E_seed_uJ: 1
Esxy_noise_cutoff: 0.002
FEL_bandwidth: 0.0015
GammaA_L1_to_L3M45eVN: 1.57
GammaKeVN: 1.49
GammaL1eVN: 8.13
GammaL3M45eVN: 0.61
GammaL3eVN: 0.61
GammarKalpha1eVN: 0.39375
GammarKalpha2eVN: 0.202668
auto_grid: false
compound:
  O:
    N_atoms: 0
    sigma_compound_Ka1: 0
    sigma_compound_pump: 0
enable_kfilter: false
enable_noise_mask: true
enable_pump_absorption: true
enable_pump_diffraction: true
enable_self_absorption: true
enable_self_diffraction: true
hwKalpha1N: 8047.91
hwKalpha2N: 8027.98
hwPump: 9000.0
is_Cartesian_pol: true
is_spontaneous_only: false
is_use_stochastic: false
n: 82.509
nlevel: 6
pump_duration_FWHM_t: 3.0
pump_pulse_format: Ocelot_SASE_pulse_pump_txy
pump_width_FWHM_x: 180
pump_width_FWHM_y: 220
random_seed: -1
run_mode: simultaneous
seed_duration_FWHM_t: 0.5
seed_pulse_format: Gaussian_pulse_aniso_seed_shifted
seed_width_FWHM_x: 480
seed_width_FWHM_y: 640
sigma1_Ka1_2p3: 1.52e-07
sigma1_Ka1_2s: 2.45e-07
sigma1_Ka1_other: 1.89e-07
sigma1_pump_1s: 2.53e-06
sigma1_pump_2p3: 1.04e-07
sigma1_pump_2s: 1.87e-07
sigma1_pump_other: 1.36e-07
sigma2_Ka1_1s: 6.53e-07
sigma2_Ka1_2p3: 4.15e-07
sigma2_Ka1_2p3_3d5: 5.01e-07
sigma2_Ka1_2s: 4.05e-07
sigma2_Ka1_other: 5.3e-08
sigma2_pump_1s: 4.75e-07
sigma2_pump_2p3: 3.02e-07
sigma2_pump_2p3_3d5: 3.67e-07
sigma2_pump_2s: 2.91e-07
sigma2_pump_other: 3.6e-08
t_peak: 1.5
tgrid: 200
tmax: 8.0
tpad: 0
turn_off_coherences: false
xgrid: 16
xmax: 1000.0
xpad: 20
ygrid: 16
ymax: 1000.0
ypad: 20
zgrid: 15
zmax: 20000.0
