#!/usr/bin/env python3
"""Run a chunk of SASE repetitions for one seed-spotsize config and save accumulated (sum/sumsq) results.

Batch-job counterpart of scripts/run_intensity_sweep.py / run_duration_sweep.py,
for the transmittance-vs-spotsize sweep generated by
scripts/generate_spotsize_sweep_configs.py: E_seed_uJ and seed_duration_FWHM_t
stay at the base config's values throughout, and what varies between configs
is seed_width_FWHM_x/y (and the matching xmax/ymax/xgrid/ygrid). Same
run_simulation/SF_spectrum_w post-processing as the other sweeps, so outputs
are directly comparable.

Output layout: one run_at_spotsize_..._reps_<start>-<end>.npz per array-task
chunk (not per repetition -- see tools.accumulate_run_outputs), all in the
same runs_spotsize_<scale>x/ folder regardless of which array task produced
them. tools.data_from_folder() combines chunks' sum/sumsq/n_reps losslessly,
so it doesn't matter how NREP was split across array tasks.

Example:
    python scripts/run_spotsize_sweep.py \\
        --yaml config/generated/transmittance_vs_spotsize/Cu-seed-SASE_spotsize2.00x.yaml \\
        --rep-start 0 --rep-end 75 --nproc 40 --data-path data/spotsize_sweep_2026-08-20
"""

import os  # noqa: E402  (must come before numpy loads)

# Set single-thread BLAS/OMP env vars before numpy loads. Each multiprocessing
# worker below gets its own NumPy; without this, each one spins up its own
# OpenBLAS/MKL thread pool and oversubscribes the cores the Pool already
# split across processes.
for _var in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS", "NUMEXPR_NUM_THREADS"):
    os.environ.setdefault(_var, "1")

import argparse  # noqa: E402
import multiprocessing as mp  # noqa: E402
import shutil  # noqa: E402

import numpy as np  # noqa: E402  (must come after the env vars above)

from XLO_sim.XLO_sim import XLO_sim  # noqa: E402
from XLO_sim import tools  # noqa: E402

TPAD = 1000
YPAD = 64


def spotsize_tag(X):
    return f"spotsize_FWHMx{X.seed_width_FWHM_x:.0f}_FWHMy{X.seed_width_FWHM_y:.0f}nm"


def run_simulation(yaml_path, rep):
    print(f"repetition {rep + 1}", flush=True)

    X = XLO_sim(yaml_path)
    X.random_seed = rep
    seed_field = tools.Ocelot_SASE_seed_pstxy(X)
    X.configure(seed_field)
    X.run_3D()

    return tools.compute_run_outputs(X, TPAD, YPAD)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yaml", required=True, help="Path to the generated config YAML for this spot-size scale")
    parser.add_argument("--rep-start", type=int, default=0, help="First repetition index (inclusive)")
    parser.add_argument("--rep-end", type=int, required=True, help="Last repetition index (exclusive)")
    parser.add_argument("--nproc", type=int, default=None,
                         help="Worker processes (default: cores actually available to this job)")
    parser.add_argument("--data-path", required=True,
                         help="Top-level output directory (shared across array tasks for the same scale)")
    args = parser.parse_args()

    nproc = args.nproc or len(os.sched_getaffinity(0))

    X = XLO_sim(args.yaml)
    run_path = os.path.join(args.data_path, f"runs_{spotsize_tag(X)}")
    os.makedirs(run_path, exist_ok=True)
    shutil.copy2(args.yaml, run_path)

    reps = list(range(args.rep_start, args.rep_end))
    print(f"Running {len(reps)} repetitions ({args.rep_start}-{args.rep_end}) for {args.yaml} "
          f"on {nproc} processes -> {run_path}", flush=True)

    ctx = mp.get_context("fork")
    with ctx.Pool(processes=nproc) as pool:
        results = pool.starmap(run_simulation, [(args.yaml, rep) for rep in reps])

    acc = tools.accumulate_run_outputs(results)
    date_string = np.datetime_as_string(np.datetime64('now'))
    np.savez_compressed(
        os.path.join(run_path, f"run_at_{spotsize_tag(X)}__reps_{args.rep_start}-{args.rep_end}_{date_string}.npz"),
        **acc,
    )


if __name__ == "__main__":
    main()
